---
# jenkins jobs

  - name: Create a jenkins job using basic authentication
    community.general.jenkins_job:
      config: "{{ lookup('file', 'templates/config.xml') }}"
      name: test_ansible
      password: "{{jenkins_password}}"
      url: "{{jenkins_server}}"
      user: "{{jenkins_user}}"