    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enable mod_rewrite in apache.
      shell: "a2enmod rewrite"
      register: a2enmodrewrite
      changed_when: "'already enabled' not in a2enmodrewrite.stdout"

# a step has not been automated, but this ansible role is executed
# on the server on which apache is installed
# so the DNS resolution must match localhost.
# Currently file /etc/hosts has been manually modified.
 
    - name: check that the server can be reached
      uri:
        url: "http://{{inventory_hostname}}"
        follow_redirects: yes

    - name:  check that the server can be reached, copy default page in /tmp
      get_url:
        url:  "http://{{inventory_hostname}}"
        dest: /tmp/index.html
        timeout: 30
