    - name: Enable the Apache2 module ssl
      apache2_module:
        state: present
        name: ssl

    - name: install certbot using apt
      apt:
        name: python3-certbot-apache
        state: present

    - name: generate certificate
      become: yes
      command: certbot certonly --standalone --non-interactive --email frederic.peignot@free.fr --agree-tos -d {{domain_name}}

