    - name: install mysql
      apt:
        pkg:
          - mysql-server
          - mysql-client
          - libmysqlclient-dev
          - python3-mysqldb
        state: present
        update_cache: true

    - name: start mysql
      service:
        name: mysql
        state: started
        enabled: yes

# Once the root password has been changed this task returns an error
    - name: Update MySQL root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Copy the root credentials as .my.cnf file
      template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
