---
# tasks file for jdk

- name: Install openksdk
  apt:
    name:
      - openjdk-{{pl_jdk_version}}-jdk
    state: latest

- name: Log the installation state
  lineinfile:
    dest: /home/ubuntu/installed.txt
    line: "{{ lookup('pipe', 'date') }} -> jdk installed"
    state: present
    insertafter: EOF
    create: True