# PHP role
#
# Install and configure PHP

  - name: Add Ondrej PPA for PHP {{php_version}}
    apt_repository:
      repo: 'ppa:ondrej/php'
      state: present
    register: ppastable

  - name: Install PHP {{php_version}} and dependencies
    apt:
      name:
        - php{{php_version}}
        - php{{php_version}}-fpm
        - php{{php_version}}-cli
        - php{{php_version}}-common
        - php{{php_version}}-opcache
        - php{{php_version}}-xml
      state: latest

  - name: Install PHP {{php_version}} and dependencies
    apt:
      name:
        - php{{php_version}}-mbstring
        - php{{php_version}}-mysql
        - php{{php_version}}-bcmath
        - php{{php_version}}-bz2
        - php{{php_version}}-curl
        - php{{php_version}}-gd
        - php{{php_version}}-intl
        - php{{php_version}}-xml
        - php{{php_version}}-zip
        - php{{php_version}}-fpm
        - libapache2-mod-php{{php_version}}
      state: latest

  - name: install a test php example
    template:
      src: "templates/info.php.j2"
      dest: "/var/www/{{lookup('env','INFRA_DOMAIN')}}/info.php"

  - name: Log the installation state
    lineinfile:
      dest: /home/ubuntu/installed.txt
      line: "{{ lookup('pipe', 'date') }} -> php {{php_version}} installed"
      state: present
      insertafter: EOF
      create: True