# PHP role
#
# Install and configure PHP

  - name: Add Ondrej PPA for PHP 8.1
    apt_repository:
      repo: 'ppa:ondrej/php'
      state: present
    register: ppastable

  - name: Install PHP 8.1 and dependencies
    apt:
      name:
        - php8.1
        - php8.1-fpm
        - php8.1-cli
        - php8.1-common
        - php8.1-opcache
      state: latest

  - name: Install PHP 8.1 and dependencies
    apt:
      name:
        - php8.1-mbstring
        - php8.1-mysql
        - php8.1-bcmath
        - php8.1-bz2
        - php8.1-curl
        - php8.1-gd
        - php8.1-intl
        - php8.1-xml
        - php8.1-zip
        - php8.1-fpm
        - libapache2-mod-php8.1
      state: latest

  - name: Log the installation state
    lineinfile:
      dest: /home/ubuntu/installed.txt
      line: "{{ lookup('pipe', 'date') }} -> php installed"
      state: present
      insertafter: EOF
      create: True