    - name: install pip
      apt: 
        pkg:
          - pip
#          - python3-dnf
      
    - name: Install pip modules
      pip:
        name: python-jenkins

    - name: Log the installation state
      lineinfile:
        dest: /home/ubuntu/installed.txt
        line: "{{ lookup('pipe', 'date') }} -> python and pip installed"
        state: present
        insertafter: EOF
        create: True