---

- name: Installing a development server

  gather_facts: true
  hosts: jenkins

  become: yes
  become_method: sudo
  become_user: root

  roles:
#    - check_access
#    - apache
#    - python
#    - https
#    - mysql
#    - php
#    - phpmyadmin
#    - phptools
#    - jdk
    - jenkins
#    - gvv

  pre_tasks:

    - name: test connection
      ping:
