---

- name: Installing a development server

  gather_facts: true
  hosts: aws_jenkins2

  become: yes
  become_method: sudo
  become_user: root

  roles:
    - check_access
#    - apache
#    - https
    - mysql
#    - ftp
#    - php
#    - gvv
#    - jdk
#    - jenkins
#    - phptools
#    - watir

  pre_tasks:

    - name: test connection
      ping:
