---

- name: Installing a continuous integration server

  gather_facts: true
  hosts: "{{ lookup('env','INFRA_HOST') }}"

  become: yes
  become_method: sudo
  become_user: root

  roles:
    #- jdk
    #- jenkins
    - phptools

  pre_tasks:

    - name: test connection
      ping:
