---

- name: Network Getting Started First Playbook
  gather_facts: true
  hosts: aws_jenkins
  tasks:

    - name: test connection
      ping:

    -name: test root access
      command: 'grep root /etc/shadow'   