---

- name: Network Getting Started First Playbook
  gather_facts: true
  hosts: jenkins
  become: yes
  become_method: sudo
  become_user: root
  
  tasks:

    - name: test connection
      ping:

    - name: test root access
      command: 'grep root /etc/shadow'   
