# phpmyadmin role
#
# Install and configure phpmyadmin

  - name: Install phpmyadmin
    apt:
      name:
        - phpmyadmin
      state: present

# From this point there are two ways to configure phpmyadmin
# Either as a subdomain which implies
# - to declare the subdomain in the S3 route to be directed to the correct IP
# - to add the subdomain to the certbot certificate
# - to create a virtual host conf for apache with correct phpmyadmin directory and certificate
# - to enable this virtual host
# - to restart apache.
#
# or to create a symbolic link to phpmyadmin
#
# Then phpmyadmin can be accessed at https://my_domain/phpmyadmin
# (use root and the mysql root password to connect)

  - name: Create a symbolic link
    file:
      src: /usr/share/phpmyadmin
      dest: "/var/www/{{lookup('env','INFRA_DOMAIN')}}/phpmyadmin"
      state: link

  - name: Restore php 8.1 as default
    ansible.builtin.shell: update-alternatives --set php /usr/bin/php8.1

#  - name: Configure Apache for phpMyAdmin
#    become: yes
#    template:
#      src: templates/apache-phpmyadmin.conf.j2
#      dest: /etc/apache2/sites-available/phpmyadmin.conf
#    notify:
#      - restart apache2

#  - name: Enable phpMyAdmin site in Apache
#    become: yes
#    command: a2ensite phpmyadmin.conf
#    notify:
#      - restart apache2

  - name: Log the installation state
    lineinfile:
      dest: /home/ubuntu/installed.txt
      line: "{{ lookup('pipe', 'date') }} -> phpmyadmin installed"
      state: present
      insertafter: EOF
      create: True
